find_program(CLANG_EXECUTABLE clang)
find_program(CLANGXX_EXECUTABLE clang++)
set(CMAKE_C_COMPILER ${CLANG_EXECUTABLE})
set(CMAKE_CXX_COMPILER ${CLANGXX_EXECUTABLE})

message("clang toolchain CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message("clang toolchain CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")

find_program(CLANG_TIDY_EXECUTABLE clang-tidy REQUIRED)
# set(CMAKE_C_CLANG_TIDY ${CLANG_TIDY_EXECUTABLE} -p ${CMAKE_BINARY_DIR})
set(CMAKE_CXX_CLANG_TIDY ${CLANG_TIDY_EXECUTABLE} -p ${CMAKE_BINARY_DIR})
